development:
  adapter: postgresql
  encoding: unicode
  database: happy_massage
  pool: 5
  username: happy_massage
  password: inicial1234

test:
  adapter: postgresql
  encoding: unicode
  database: happy_massage
  pool: 5
  username: happy_massage
  password: inicial1234
