development:
  adapter: postgresql
  encoding: unicode
  database: happy_massage
  pool: 5
  username: happy_massage
  password: inicial1234

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: happy_massage
  password: inicial1234

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: happy_massage
  password: inicial1234